# Generated by Django 2.2.5 on 2019-09-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectableObject',
            fields=[
                ('tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('singular', models.CharField(max_length=50)),
                ('plural', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DetectableObject',
                'verbose_name_plural': 'DetectableObjects',
                'db_table': 'DetectableObject',
            },
        ),
        migrations.CreateModel(
            name='DetectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('original_image', models.ImageField(upload_to='images/originals/')),
            ],
            options={
                'verbose_name': 'DetectionRequest',
                'verbose_name_plural': 'DetectionRequests',
                'db_table': 'DetectionRequest',
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('created_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('object_count', models.IntegerField()),
                ('tag_count', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('tagged_image', models.ImageField(upload_to='images/tagged/')),
                ('human_readable', models.CharField(max_length=500)),
                ('detection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.DetectionRequest')),
            ],
            options={
                'verbose_name': 'DetectionResponse',
                'verbose_name_plural': 'DetectionResponses',
                'db_table': 'DetectionResponse',
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_rate', models.DecimalField(decimal_places=16, max_digits=22)),
                ('x_right', models.DecimalField(decimal_places=16, max_digits=22)),
                ('x_left', models.DecimalField(decimal_places=16, max_digits=22)),
                ('y_right', models.DecimalField(decimal_places=16, max_digits=22)),
                ('y_left', models.DecimalField(decimal_places=16, max_digits=22)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DetectableObject')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DetectionResult')),
            ],
            options={
                'verbose_name': 'DetectedObject',
                'verbose_name_plural': 'DetectedObjects',
                'db_table': 'DetectedObject',
            },
        ),
    ]
