# Generated by Django 2.2.5 on 2019-09-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedobject',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='detectedobject',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='detection_request',
        ),
        migrations.DeleteModel(
            name='DetectableObject',
        ),
        migrations.DeleteModel(
            name='DetectedObject',
        ),
        migrations.DeleteModel(
            name='DetectionRequest',
        ),
        migrations.DeleteModel(
            name='DetectionResult',
        ),
    ]
